<a href="https://colab.research.google.com/github/ilamaalajmah/Sales-Data-Analysis-Project/blob/main/Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# Sales Performance Analysis

In [2]:
#install the libraries:-
import pandas as pd
import numpy as np

In [5]:
#Task1/
#read the file
df = pd.read_csv("/content/sales_data_sample.csv", encoding="latin1")
print(f"first 5 rows is: {df.head(5)}")
print(f"last 5 rows is: {df.tail(5)}")

first 5 rows is:    ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0        10107               30      95.70                2  2871.00
1        10121               34      81.35                5  2765.90
2        10134               41      94.74                2  3884.34
3        10145               45      83.26                6  3746.70
4        10159               49     100.00               14  5205.27

         ORDERDATE   STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0   2/24/2003 0:00  Shipped       1         2     2003  ...
1    5/7/2003 0:00  Shipped       2         5     2003  ...
2    7/1/2003 0:00  Shipped       3         7     2003  ...
3   8/25/2003 0:00  Shipped       3         8     2003  ...
4  10/10/2003 0:00  Shipped       4        10     2003  ...

                    ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0        897 Long Airport Avenue           NaN            NYC    NY
1             59 rue de l'Abbaye           NaN          Reims   NaN
2  27 rue du Colonel Pierre Avia           NaN          Paris   NaN
3             78934 Hillside Dr.           NaN       Pasadena    CA
4                7734 Strong St.           NaN  San Francisco    CA

  POSTALCODE COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE
0      10022     USA       NaN              Yu             Kwai    Small
1      51100  France      EMEA         Henriot             Paul    Small
2      75508  France      EMEA        Da Cunha           Daniel   Medium
3      90003     USA       NaN           Young            Julie   Medium
4        NaN     USA       NaN           Brown            Julie   Medium

[5 rows x 25 columns]
last 5 rows is:       ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
2818        10350               20     100.00               15  2244.40
2819        10373               29     100.00                1  3978.51
2820        10386               43     100.00                4  5417.57
2821        10397               34      62.24                1  2116.16
2822        10414               47      65.52                9  3079.44

           ORDERDATE    STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
2818  12/2/2004 0:00   Shipped       4        12     2004  ...
2819  1/31/2005 0:00   Shipped       1         1     2005  ...
2820   3/1/2005 0:00  Resolved       1         3     2005  ...
2821  3/28/2005 0:00   Shipped       1         3     2005  ...
2822   5/6/2005 0:00   On Hold       2         5     2005  ...

               ADDRESSLINE1  ADDRESSLINE2      CITY STATE POSTALCODE  COUNTRY  \
2818     C/ Moralzarzal, 86           NaN    Madrid   NaN      28034    Spain
2819            Torikatu 38           NaN      Oulu   NaN      90110  Finland
2820     C/ Moralzarzal, 86           NaN    Madrid   NaN      28034    Spain
2821  1 rue Alsace-Lorraine           NaN  Toulouse   NaN      31000   France
2822     8616 Spinnaker Dr.           NaN    Boston    MA      51003      USA

     TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE
2818      EMEA          Freyre            Diego    Small
2819      EMEA       Koskitalo           Pirkko   Medium
2820      EMEA          Freyre            Diego   Medium
2821      EMEA          Roulet          Annette    Small
2822       NaN         Yoshido             Juri   Medium

[5 rows x 25 columns]

In [62]:
#Task2/
print(f"Sum of rows = {df.shape[0]}")
print(f"Sum of columns = {df.shape[1]}")
print(f"The name of the columns is: {list(df.columns)}")
print(f"The Types of the columns is: {df.dtypes}")

Sum of rows = 2823
Sum of columns = 25
The name of the columns is: ['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER', 'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID', 'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE', 'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE', 'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'DEALSIZE']
The Types of the columns is: ORDERNUMBER           int64
QUANTITYORDERED       int64
PRICEEACH           float64
ORDERLINENUMBER       int64
SALES               float64
ORDERDATE            object
STATUS               object
QTR_ID                int64
MONTH_ID              int64
YEAR_ID               int64
PRODUCTLINE          object
MSRP                  int64
PRODUCTCODE          object
CUSTOMERNAME         object
PHONE                object
ADDRESSLINE1         object
ADDRESSLINE2         object
CITY                 object
STATE                object
POSTALCODE           object
COUNTRY              object
TERRITORY            object
CONTACTLASTNAME      object
CONTACTFIRSTNAME     object
DEALSIZE             object
dtype: object

In [15]:
#Task3/
display(df.describe())
display(df.describe(include="object"))

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2.717676,7.092455,2003.81509,100.715551
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912
min,10100.000000,6.000000,26.880000,1.000000,482.130000,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,4.000000,12.000000,2005.00000,214.000000

,ORDERDATE,STATUS,PRODUCTLINE,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
count,2823,2823,2823,2823,2823,2823,2823,302,2823,1337,2747,2823,1749,2823,2823,2823
unique,252,6,7,109,92,91,92,9,73,16,73,19,3,77,72,3
top,11/14/2003 0:00,Shipped,Classic Cars,S18_3232,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Level 3,Madrid,CA,28034,USA,EMEA,Freyre,Diego,Medium
freq,38,2617,967,52,259,259,259,55,304,416,259,1004,1407,259,259,1384

In [39]:
#Task4/
print(np.mean(df["SALES"]))
print(np.median(df["SALES"]))
print(np.min(df["SALES"]))
print(np.max(df["SALES"]))

3553.889071909316
3184.8
482.13
14082.8

In [42]:
#Task5/
display(df[["ORDERLINENUMBER","CUSTOMERNAME","SALES"]])

      ORDERLINENUMBER              CUSTOMERNAME    SALES
0                   2         Land of Toys Inc.  2871.00
1                   5        Reims Collectables  2765.90
2                   2           Lyon Souveniers  3884.34
3                   6         Toys4GrownUps.com  3746.70
4                  14  Corporate Gift Ideas Co.  5205.27
...               ...                       ...      ...
2818               15     Euro Shopping Channel  2244.40
2819                1   Oulu Toy Supplies, Inc.  3978.51
2820                4     Euro Shopping Channel  5417.57
2821                1              Alpha Cognac  2116.16
2822                9         Gifts4AllAges.com  3079.44

[2823 rows x 3 columns]

In [47]:
#Task6/
display(df.iloc[10:21:])

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
10,10223,37,100.00,1,3965.66,2/20/2004 0:00,Shipped,1,2,2004,...,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,APAC,Ferguson,Peter,Medium
11,10237,23,100.00,7,2333.12,4/5/2004 0:00,Shipped,2,4,2004,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,NaN,Frick,Michael,Small
12,10251,28,100.00,2,3188.64,5/18/2004 0:00,Shipped,2,5,2004,...,7476 Moss Rd.,NaN,Newark,NJ,94019,USA,NaN,Brown,William,Medium
13,10263,34,100.00,2,3676.76,6/28/2004 0:00,Shipped,2,6,2004,...,25593 South Bay Ln.,NaN,Bridgewater,CT,97562,USA,NaN,King,Julie,Medium
14,10275,45,92.83,1,4177.35,7/23/2004 0:00,Shipped,3,7,2004,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium
15,10285,36,100.00,6,4099.68,8/27/2004 0:00,Shipped,3,8,2004,...,39323 Spinnaker Dr.,NaN,Cambridge,MA,51247,USA,NaN,Hernandez,Marta,Medium
16,10299,23,100.00,9,2597.39,9/30/2004 0:00,Shipped,3,9,2004,...,Keskuskatu 45,NaN,Helsinki,NaN,21240,Finland,EMEA,Karttunen,Matti,Small
17,10309,41,100.00,5,4394.38,10/15/2004 0:00,Shipped,4,10,2004,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
18,10318,46,94.74,1,4358.04,11/2/2004 0:00,Shipped,4,11,2004,...,7586 Pompton St.,NaN,Allentown,PA,70267,USA,NaN,Yu,Kyung,Medium
19,10329,42,100.00,1,4396.14,11/15/2004 0:00,Shipped,4,11,2004,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
20,10341,41,100.00,9,7737.93,11/24/2004 0:00,Shipped,4,11,2004,...,Geislweg 14,NaN,Salzburg,NaN,5020,Austria,EMEA,Pipps,Georg,Large

In [56]:
#Task7/
display(df.loc[df["ORDERNUMBER"]==10100])

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
578,10100,30,100.00,3,5151.00,1/6/2003 0:00,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Medium
680,10100,50,67.80,2,3390.00,1/6/2003 0:00,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Medium
1267,10100,22,86.51,4,1903.22,1/6/2003 0:00,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Small
2024,10100,49,34.47,1,1689.03,1/6/2003 0:00,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Small

In [71]:
#Task8/

sales_df = pd.DataFrame({
    "PRODUCTLINE" : df['PRODUCTLINE'],
"COUNTRY" : df["COUNTRY"],
"SALES" :df["SALES"]
})
display(sales_df)

      PRODUCTLINE  COUNTRY    SALES
0     Motorcycles      USA  2871.00
1     Motorcycles   France  2765.90
2     Motorcycles   France  3884.34
3     Motorcycles      USA  3746.70
4     Motorcycles      USA  5205.27
...           ...      ...      ...
2818        Ships    Spain  2244.40
2819        Ships  Finland  3978.51
2820        Ships    Spain  5417.57
2821        Ships   France  2116.16
2822        Ships      USA  3079.44

[2823 rows x 3 columns]

In [94]:
#Task9/
display(df.loc[df['SALES']>5000])

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
4,10159,49,100.0,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
7,10188,48,100.0,1,5512.32,11/18/2003 0:00,Shipped,4,11,2003,...,"Drammen 121, PR 744 Sentrum",NaN,Bergen,NaN,N 5804,Norway,EMEA,Oeztan,Veysel,Medium
20,10341,41,100.0,9,7737.93,11/24/2004 0:00,Shipped,4,11,2004,...,Geislweg 14,NaN,Salzburg,NaN,5020,Austria,EMEA,Pipps,Georg,Large
25,10417,66,100.0,2,7516.08,5/13/2005 0:00,Disputed,2,5,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Large
26,10103,26,100.0,11,5404.62,1/29/2003 0:00,Shipped,1,1,2003,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2685,10361,44,100.0,10,5001.92,12/17/2004 0:00,Shipped,4,12,2004,...,"Monitor Money Building, 815 Pacific Hwy",Level 6,Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Medium
2686,10375,44,100.0,11,5208.72,2/3/2005 0:00,Shipped,1,2,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium
2689,10401,77,92.0,9,7084.00,4/3/2005 0:00,On Hold,2,4,2005,...,7476 Moss Rd.,NaN,Newark,NJ,94019,USA,NaN,Brown,William,Large
2715,10397,48,100.0,3,5192.64,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Medium
2820,10386,43,100.0,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium

In [96]:
#Task10/
display(df[df['COUNTRY']=="USA"])

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
5,10168,36,96.66,1,3479.76,10/28/2003 0:00,Shipped,4,10,2003,...,9408 Furth Circle,NaN,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Medium
8,10201,22,98.57,2,2168.54,12/1/2003 0:00,Shipped,4,12,2003,...,5557 North Pendale Street,NaN,San Francisco,CA,NaN,USA,NaN,Murphy,Julie,Small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2804,10185,28,64.43,6,1804.04,11/14/2003 0:00,Shipped,4,11,2003,...,4575 Hillside Dr.,NaN,New Bedford,MA,50553,USA,NaN,Tam,Wing C,Small
2807,10222,36,63.34,18,2280.24,2/19/2004 0:00,Shipped,1,2,2004,...,361 Furth Circle,NaN,San Diego,CA,91217,USA,NaN,Thompson,Valarie,Small
2809,10248,23,65.52,9,1506.96,5/7/2004 0:00,Cancelled,2,5,2004,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
2817,10337,42,97.16,5,4080.72,11/21/2004 0:00,Shipped,4,11,2004,...,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,NaN,Hernandez,Maria,Medium
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [104]:
#Task11/
display(df[df["COUNTRY"].isin(["USA","France"])])

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2809,10248,23,65.52,9,1506.96,5/7/2004 0:00,Cancelled,2,5,2004,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
2815,10315,40,55.69,5,2227.60,10/29/2004 0:00,Shipped,4,10,2004,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Small
2817,10337,42,97.16,5,4080.72,11/21/2004 0:00,Shipped,4,11,2004,...,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,NaN,Hernandez,Maria,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [112]:
#Task12/
display(df[ (df["PRODUCTLINE"] == 'Classic Cars')
&
            (df["SALES"] > 3000)
            ])

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
26,10103,26,100.00,11,5404.62,1/29/2003 0:00,Shipped,1,1,2003,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
27,10112,29,100.00,1,7209.11,3/24/2003 0:00,Shipped,1,3,2003,...,Berguvsvgen 8,NaN,Lule,NaN,S-958 22,Sweden,EMEA,Berglund,Christina,Large
28,10126,38,100.00,11,7329.06,5/28/2003 0:00,Shipped,2,5,2003,...,"C/ Araquil, 67",NaN,Madrid,NaN,28023,Spain,EMEA,Sommer,Mart¡n,Large
29,10140,37,100.00,11,7374.10,7/24/2003 0:00,Shipped,3,7,2003,...,9408 Furth Circle,NaN,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Large
30,10150,45,100.00,8,10993.50,9/19/2003 0:00,Shipped,3,9,2003,...,"Bronz Sok., Bronz Apt. 3/6 Tesvikiye",NaN,Singapore,NaN,79903,Singapore,Japan,Natividad,Eric,Large
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2634,10336,46,100.00,2,9558.80,11/20/2004 0:00,Shipped,4,11,2004,...,"265, boulevard Charonne",NaN,Paris,NaN,75012,France,EMEA,Bertrand,Marie,Large
2636,10358,27,100.00,3,3761.37,12/10/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2637,10371,34,100.00,3,4301.34,1/23/2005 0:00,Shipped,1,1,2005,...,5677 Strong St.,NaN,San Rafael,CA,97562,USA,NaN,Nelson,Valarie,Medium
2639,10411,34,100.00,4,3576.80,5/1/2005 0:00,Shipped,2,5,2005,...,43 rue St. Laurent,NaN,Montreal,Quebec,H1J 1C3,Canada,NaN,Fresnisre,Jean,Medium
2640,10424,46,80.92,1,3722.32,5/31/2005 0:00,In Process,2,5,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium

In [6]:
#Task14
df['TOTAL_VALUE']= df['QUANTITYORDERED'] * df['PRICEEACH']
display(df['TOTAL_VALUE'])

0       2871.00
1       2765.90
2       3884.34
3       3746.70
4       4900.00
         ...
2818    2000.00
2819    2900.00
2820    4300.00
2821    2116.16
2822    3079.44
Name: TOTAL_VALUE, Length: 2823, dtype: float64

In [7]:
#Task15
df['DISCOUNT_FLAG'] = np.where(df["SALES"] > 5000, "High", "Normal")
df['DISCOUNT_FLAG']

0       Normal
1       Normal
2       Normal
3       Normal
4         High
         ...
2818    Normal
2819    Normal
2820      High
2821    Normal
2822    Normal
Name: DISCOUNT_FLAG, Length: 2823, dtype: object

In [8]:
#Task17
df['BIG_ORDER'] = np.where(df["QUANTITYORDERED"] >= 40, "Yes", "No")
df['BIG_ORDER']

0        No
1        No
2       Yes
3       Yes
4       Yes
       ...
2818     No
2819     No
2820    Yes
2821     No
2822    Yes
Name: BIG_ORDER, Length: 2823, dtype: object

In [16]:
#Task18
display(df.isnull().sum())
print("---------")
display(df.apply(lambda x: x.isnull().sum() / len(df) * 100))

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
TOTAL_VALUE            0
DISCOUNT_FLAG          0
BIG_ORDER              0
dtype: int64

---------

ORDERNUMBER          0.000000
QUANTITYORDERED      0.000000
PRICEEACH            0.000000
ORDERLINENUMBER      0.000000
SALES                0.000000
ORDERDATE            0.000000
STATUS               0.000000
QTR_ID               0.000000
MONTH_ID             0.000000
YEAR_ID              0.000000
PRODUCTLINE          0.000000
MSRP                 0.000000
PRODUCTCODE          0.000000
CUSTOMERNAME         0.000000
PHONE                0.000000
ADDRESSLINE1         0.000000
ADDRESSLINE2        89.302161
CITY                 0.000000
STATE               52.639036
POSTALCODE           2.692171
COUNTRY              0.000000
TERRITORY           38.044633
CONTACTLASTNAME      0.000000
CONTACTFIRSTNAME     0.000000
DEALSIZE             0.000000
TOTAL_VALUE          0.000000
DISCOUNT_FLAG        0.000000
BIG_ORDER            0.000000
dtype: float64

In [33]:
#Task19
duplicate = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate}")

Number of duplicate rows: 0

In [44]:
#Task21
print(f"the sum of each sale {df.groupby('COUNTRY')['SALES'].sum().sort_values(ascending=False)} ")

the sum of each sale COUNTRY
USA            3627982.83
Spain          1215686.92
France         1110916.52
Australia       630623.10
UK              478880.46
Italy           374674.31
Finland         329581.91
Norway          307463.70
Singapore       288488.41
Denmark         245637.15
Canada          224078.56
Germany         220472.09
Sweden          210014.21
Austria         202062.53
Japan           188167.81
Switzerland     117713.56
Belgium         108412.62
Philippines      94015.73
Ireland          57756.43
Name: SALES, dtype: float64

In [46]:
#Task22
print(df.groupby('PRODUCTLINE')['SALES'].mean())

PRODUCTLINE
Classic Cars        4053.377104
Motorcycles         3523.831843
Planes              3186.286176
Ships               3053.150128
Trains              2938.226883
Trucks and Buses    3746.810100
Vintage Cars        3135.339110
Name: SALES, dtype: float64

In [53]:
#Task23
display(df.groupby('COUNTRY')['SALES'].agg(['sum','count','max','mean']))

                    sum  count       max         mean
COUNTRY
Australia     630623.10    185   9774.03  3408.773514
Austria       202062.53     55   9240.00  3673.864182
Belgium       108412.62     33   6804.63  3285.230909
Canada        224078.56     70   9064.89  3201.122286
Denmark       245637.15     63  10468.90  3899.002381
Finland       329581.91     92  10606.20  3582.412065
France       1110916.52    314  11739.70  3537.950701
Germany       220472.09     62   8940.96  3556.001452
Ireland        57756.43     16   8258.00  3609.776875
Italy         374674.31    113   9160.36  3315.701858
Japan         188167.81     52  10758.00  3618.611731
Norway        307463.70     85   8844.12  3617.220000
Philippines    94015.73     26   7483.98  3615.989615
Singapore     288488.41     79  10993.50  3651.752025
Spain        1215686.92    342  12001.00  3554.640117
Sweden        210014.21     57   7209.11  3684.459825
Switzerland   117713.56     31   6761.60  3797.211613
UK            478880.46    144  11886.60  3325.558750
USA          3627982.83   1004  14082.80  3613.528715

In [61]:
#Task24
sales_by_country_product = df.pivot_table(
    index='COUNTRY',
    columns='PRODUCTLINE',
    values='SALES',
    aggfunc='sum',
    fill_value=0

)
display(sales_by_country_product)

PRODUCTLINE,Classic Cars,Motorcycles,Planes,Ships,Trains,Trucks and Buses,Vintage Cars
COUNTRY,,,,,,,
Australia,193085.54,89968.76,74853.87,4159.76,1681.35,77318.50,189555.32
Austria,101459.47,26047.66,17860.44,9024.73,0.00,20472.75,27197.48
Belgium,20136.96,0.00,5624.79,31708.01,9017.26,0.00,41925.60
Canada,61623.22,4177.49,25510.07,40309.01,0.00,51945.98,40512.79
Denmark,157182.48,0.00,7586.45,38697.26,11476.33,9588.82,21105.81
Finland,153552.24,47866.72,34375.13,29808.44,5117.05,40479.33,18383.00
France,388951.20,226390.31,108155.51,66486.67,27340.80,116982.22,176609.81
Germany,148315.00,7497.50,23001.26,5501.00,5043.42,10178.00,20935.91
Ireland,31688.82,4953.20,11784.36,0.00,3112.60,3983.05,2234.40
Italy,128576.65,7567.80,98185.65,17703.54,6274.96,5914.97,110450.74
Japan,47271.49,26536.41,49176.96,18860.02,3523.67,13349.44,29449.82
Norway,134787.37,51768.63,29500.70,0.00,11310.36,37075.64,43021.00
Philippines,53112.09,18061.68,20906.87,0.00,0.00,0.00,1935.09
Singapore,132890.44,4175.60,0.00,14155.52,13278.71,89027.68,34960.46
Spain,476165.15,74634.82,89985.51,124459.97,43370.18,177556.78,229514.51
Sweden,69088.06,15567.25,8899.60,30915.89,3807.68,47931.27,33804.46
Switzerland,117713.56,0.00,0.00,0.00,0.00,0.00,0.00
UK,159377.70,40802.81,41163.51,72959.17,12635.54,28142.99,123798.74
USA,1344638.22,520371.70,328432.89,209688.14,69253.56,397842.42,757755.90

In [60]:
#Task25
orders_by_year_status = df.pivot_table(
    index='YEAR_ID',
    columns='STATUS',
    values='SALES',
    aggfunc='count',
    fill_value=0

)
display(orders_by_year_status)

STATUS   Cancelled  Disputed  In Process  On Hold  Resolved  Shipped
YEAR_ID
2003            16         0           0        0         8      976
2004            44         0           0        6         8     1287
2005             0        14          41       38        31      354

In [70]:
#Task 27
df['ORDER-DATE'] = pd.to_datetime(df['ORDERDATE'])

In [71]:
#Task28
df['year'] = df['ORDER-DATE'].dt.year
df['month'] = df['ORDER-DATE'].dt.month
df['day'] = df['ORDER-DATE'].dt.day
df['day_name'] = df['ORDER-DATE'].dt.day_name()

display(df['year'])
display(df['month'])
display(df['day'])
display(df['day_name'])

0       2003
1       2003
2       2003
3       2003
4       2003
        ...
2818    2004
2819    2005
2820    2005
2821    2005
2822    2005
Name: year, Length: 2823, dtype: int32

0        2
1        5
2        7
3        8
4       10
        ..
2818    12
2819     1
2820     3
2821     3
2822     5
Name: month, Length: 2823, dtype: int32

0       24
1        7
2        1
3       25
4       10
        ..
2818     2
2819    31
2820     1
2821    28
2822     6
Name: day, Length: 2823, dtype: int32

0          Monday
1       Wednesday
2         Tuesday
3          Monday
4          Friday
          ...
2818     Thursday
2819       Monday
2820      Tuesday
2821       Monday
2822       Friday
Name: day_name, Length: 2823, dtype: object

In [ ]:
#THE END!